<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKC0LzDe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKC0LzDe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKC0LzDe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKC0LzDe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKC0LzDe\App_KernelDevDebugContainer([
    'container.build_hash' => 'KC0LzDe',
    'container.build_id' => '7044b689',
    'container.build_time' => 1700060103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKC0LzDe');
