<?php

namespace ContainerL1hTkbD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DPnUVoEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dPnUVoE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dPnUVoE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paquetRepository' => ['privates', 'App\\Repository\\PaquetRepository', 'getPaquetRepositoryService', true],
        ], [
            'paquetRepository' => 'App\\Repository\\PaquetRepository',
        ]);
    }
}
