<?php

namespace ContainerL1hTkbD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.75.FvYQ.App\Entity\Carte' shared service.
     *
     * @return \App\Entity\Carte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.75.FvYQ": it needs an instance of "App\\Entity\\Carte" but this type has been excluded in "config/services.yaml".');
    }
}
