<?php

namespace ContainerL1hTkbD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaquet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7ldIKVQ.App\Entity\Paquet' shared service.
     *
     * @return \App\Entity\Paquet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7ldIKVQ": it needs an instance of "App\\Entity\\Paquet" but this type has been excluded in "config/services.yaml".');
    }
}
