<?php

namespace ContainerKC0LzDe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7ldIKVQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7ldIKVQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7ldIKVQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paquet' => ['privates', '.errored..service_locator.7ldIKVQ.App\\Entity\\Paquet', NULL, 'Cannot autowire service ".service_locator.7ldIKVQ": it needs an instance of "App\\Entity\\Paquet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'paquet' => 'App\\Entity\\Paquet',
        ]);
    }
}
