<?php

namespace ContainerKC0LzDe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YAB3ekrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YAB3ekr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YAB3ekr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carteRepository' => ['privates', 'App\\Repository\\CarteRepository', 'getCarteRepositoryService', true],
        ], [
            'carteRepository' => 'App\\Repository\\CarteRepository',
        ]);
    }
}
