<?php

namespace ContainerKC0LzDe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarte2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KQpIb2I.App\Entity\Carte' shared service.
     *
     * @return \App\Entity\Carte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KQpIb2I": it needs an instance of "App\\Entity\\Carte" but this type has been excluded in "config/services.yaml".');
    }
}
